load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_NetworkManagement"
   ,  srcs       = ["aapFunctionalCluster_NetworkManagement.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_NetworkManagement_NetworkHandle.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

